maven2.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -28,20 +28,24 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
-    - name: Build with Maven
-      run: mvn -B clean verify --file Calidad-Maven/pom.xml
+    - name: Build with Maven and enable debug
+      run: mvn -B -e -U clean verify --file Calidad-Maven/pom.xml
 
     - name: Publish JaCoCo Coverage Report
+      if: success() || failure() # This ensures that artifacts are uploaded even if the build fails
       uses: actions/upload-artifact@v3
       with:
         name: jacoco-report
         path: Calidad-Maven/target/site/jacoco/
 
     - name: Generate Allure report
+      if: success() # This step will run only if the build succeeds
       run: mvn allure:report -f Calidad-Maven/pom.xml
 
     - name: Publish Allure Report
+      if: success() # This step will run only if the build succeeds
       uses: actions/upload-artifact@v3
       with:
         name: allure-report
         path: Calidad-Maven/target/site/allure-maven-plugin
+
